name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Build dilakukan di server GitHub (RAM 7GB)
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t zhafir-portfolio:latest .

    - name: Save Docker Image to Tarball
      run: docker save zhafir-portfolio:latest > zhafir-portfolio.tar

    - name: Transfer Image to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 2204
        source: "zhafir-portfolio.tar"
        target: "~/" # Dikirim ke direktori home VPS

    - name: Load and Deploy on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 2204
        script: |
          # 1. Load image dari file tar yang dikirim
          docker load < ~/zhafir-portfolio.tar
          
          # 2. Hapus file tar untuk menghemat storage
          rm ~/zhafir-portfolio.tar

          # 3. Re-deploy Container
          docker stop zhafir-portfolio || true
          docker rm zhafir-portfolio || true

          docker run -d \
            --name zhafir-portfolio \
            -p 6969:6969 \
            --restart always \
            zhafir-portfolio:latest

          # 4. Bersihkan image lama agar disk 60GB tidak penuh
          docker image prune -f